apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackit-maintenance-exporter
  namespace: monitoring
  labels:
    app: stackit-maintenance-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackit-maintenance-exporter
  template:
    metadata:
      labels:
        app: stackit-maintenance-exporter
    spec:
      containers:
        - name: exporter
          imagePullPolicy: Always
          image: ghcr.io/h3adex/stackit-server-maintenance-exporter:sha256-75c8215bba5cd5298c76c91d84a0c0528a94a176513ed748b756e2917ac6e3c5
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: sae
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"